service: api-proy
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9    
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  iam:
    role: arn:aws:iam::223794358031:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-meds-table
    BUCKET_IMG: ${sls:stage}-meds-imagen

  region: us-east-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:

    # aws lambda has an after-extraction size limit - with native dependencies we pass the limit quickly
    # zip the requirements and extract them on the fly (see handler.py)
    zip: true

package:
  # exclude everything...
  exclude:
    - '**/*'

  # include - we have to explicitly list packages with native dependencies.
  include:
    - '*.py'
    - 'amazon-textract-response-parser'

functions:
  registroEntradaSalida:
    handler: api-medicamentos/registro_entrada_salida.lambda_handler
    events:
      - http:
          path: registroEntradaSalida
          method: post
          cors: true
  # crear:
  #   handler: comentario.lambda_handler
  #   memorySize: 512
  #   events:
  #     - http:
  #         path: /comentario/crear
  #         method: post
  #         # Enable CORS. Don't forget to return the right header in your response
  #         cors: true
  #         integration: lambda
  scan_meds:
    handler: scan_meds.lambda_handler
    events:
      - s3:
          bucket: ${sls:stage}-meds-imagen
          event: s3:ObjectCreated:*
  new_meds:
    handler: new_meds.lambda_handler
    events:
      - sns: arn:aws:sns:us-east-1:223794358031:NuevoMedicamento

resources:
  Resources:
    TablaMedicinas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: fabricant_id
            AttributeType: S
          - AttributeName: info
            AttributeType: S
        KeySchema:
          - AttributeName: fabricant_id
            KeyType: HASH
          - AttributeName: info
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    RegistroEntradaSalidaTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'RegistroEntradaSalida'
        AttributeDefinitions:
          - AttributeName: 'employee_id'
            AttributeType: 'S'
          - AttributeName: 'timestamp'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'employee_id'
            KeyType: 'HASH'
          - AttributeName: 'timestamp'
            KeyType: 'RANGE'
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    # IMGBucket:

    # IMGBucket:
    #   Type: AWS::S3::Bucket
    #   Properties:
    #     BucketName: ${self:provider.environment.BUCKET_IMG}
    #     AccessControl: Private
